-- Live Tag operational layer (apply on authorized release only)

ALTER TABLE "AnalysisSession" ADD COLUMN IF NOT EXISTS "liveClock" JSONB;
ALTER TABLE "AnalysisSession" ADD COLUMN IF NOT EXISTS "collectiveNotes" TEXT;

ALTER TABLE "AnalysisTagDefinition" ADD COLUMN IF NOT EXISTS "shortcutKey" TEXT;
ALTER TABLE "AnalysisTagDefinition" ADD COLUMN IF NOT EXISTS "requiresPlayer" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AnalysisTagDefinition" ADD COLUMN IF NOT EXISTS "autoClipEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AnalysisTagDefinition" ADD COLUMN IF NOT EXISTS "autoClipPreMs" INTEGER NOT NULL DEFAULT 8000;
ALTER TABLE "AnalysisTagDefinition" ADD COLUMN IF NOT EXISTS "autoClipPostMs" INTEGER NOT NULL DEFAULT 4000;

ALTER TABLE "AnalysisEvent" ADD COLUMN IF NOT EXISTS "analysisClass" TEXT;

ALTER TABLE "AnalysisClip" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AnalysisClip" ADD COLUMN IF NOT EXISTS "sourceEventId" TEXT;

CREATE TABLE IF NOT EXISTS "AnalysisPlayerMaterialItem" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "analysisSessionId" TEXT NOT NULL,
    "playerId" TEXT NOT NULL,
    "eventId" TEXT,
    "clipId" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT,
    "authorUserId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AnalysisPlayerMaterialItem_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "AnalysisPlayerMaterialItem_tenantId_analysisSessionId_playerId_idx" ON "AnalysisPlayerMaterialItem"("tenantId", "analysisSessionId", "playerId");
CREATE INDEX IF NOT EXISTS "AnalysisPlayerMaterialItem_eventId_idx" ON "AnalysisPlayerMaterialItem"("eventId");
CREATE INDEX IF NOT EXISTS "AnalysisPlayerMaterialItem_clipId_idx" ON "AnalysisPlayerMaterialItem"("clipId");

ALTER TABLE "AnalysisPlayerMaterialItem" ADD CONSTRAINT "AnalysisPlayerMaterialItem_analysisSessionId_fkey" FOREIGN KEY ("analysisSessionId") REFERENCES "AnalysisSession"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AnalysisPlayerMaterialItem" ADD CONSTRAINT "AnalysisPlayerMaterialItem_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "Player"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AnalysisPlayerMaterialItem" ADD CONSTRAINT "AnalysisPlayerMaterialItem_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "AnalysisEvent"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AnalysisPlayerMaterialItem" ADD CONSTRAINT "AnalysisPlayerMaterialItem_clipId_fkey" FOREIGN KEY ("clipId") REFERENCES "AnalysisClip"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "AnalysisClip" ADD CONSTRAINT "AnalysisClip_sourceEventId_fkey" FOREIGN KEY ("sourceEventId") REFERENCES "AnalysisEvent"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS "AnalysisClip_sourceEventId_idx" ON "AnalysisClip"("sourceEventId");
