/** Catálogo inicial de fisioterapia (reunião + regiões típicas do futebol). */

export const PHYSIO_REGIONS: Array<{
  id: string;
  namePt: string;
  sortOrder: number;
  bilateral: boolean;
}> = [
  { id: "cabeca", namePt: "Cabeça", sortOrder: 10, bilateral: false },
  { id: "coluna_cervical", namePt: "Coluna cervical", sortOrder: 20, bilateral: false },
  { id: "coluna_toracica", namePt: "Coluna torácica", sortOrder: 30, bilateral: false },
  { id: "coluna_lombar", namePt: "Coluna lombar", sortOrder: 40, bilateral: false },
  { id: "ombro", namePt: "Ombro", sortOrder: 50, bilateral: true },
  { id: "braco", namePt: "Braço", sortOrder: 60, bilateral: true },
  { id: "cotovelo", namePt: "Cotovelo", sortOrder: 70, bilateral: true },
  { id: "antebraco", namePt: "Antebraço", sortOrder: 80, bilateral: true },
  { id: "punho", namePt: "Punho", sortOrder: 90, bilateral: true },
  { id: "mao", namePt: "Mão", sortOrder: 100, bilateral: true },
  { id: "pelve", namePt: "Pelve", sortOrder: 110, bilateral: false },
  { id: "quadril", namePt: "Quadril", sortOrder: 120, bilateral: true },
  { id: "coxa", namePt: "Coxa", sortOrder: 130, bilateral: true },
  { id: "joelho", namePt: "Joelho", sortOrder: 140, bilateral: true },
  { id: "perna", namePt: "Perna", sortOrder: 150, bilateral: true },
  { id: "tornozelo", namePt: "Tornozelo", sortOrder: 160, bilateral: true },
  { id: "pe", namePt: "Pé", sortOrder: 170, bilateral: true },
];

export const PHYSIO_DIAGNOSES_BY_REGION: Record<string, string[]> = {
  cabeca: [
    "Fratura do crânio",
    "Fratura da base do crânio",
    "Fratura frontal",
    "Fratura temporal",
    "Fratura parietal",
    "Fratura occipital",
    "Fratura nasal",
    "Fratura do zigomático",
    "Fratura orbitária",
    "Fratura maxilar",
    "Fratura mandibular",
    "Fraturas Le Fort I",
    "Le Fort II",
    "Le Fort III",
    "Disfunção temporomandibular",
    "Luxação da ATM",
    "Hipermobilidade da ATM",
    "Osteoartrose da ATM",
    "Artrite da ATM",
    "Anquilose da ATM",
    "Bruxismo",
    "Dor miofascial mastigatória",
    "Concussão",
    "Contusão craniofacial",
  ],
  coluna_cervical: [
    "Cervicalgia",
    "Torcicolo",
    "Whiplash",
    "Hérnia cervical",
    "Protusão discal",
    "Abaulamento discal",
    "Espondilose cervical",
    "Estenose cervical",
    "Radiculopatia cervical",
    "Mielopatia cervical",
    "Síndrome facetária",
    "Síndrome miofascial",
    "Instabilidade cervical",
    "Fraturas cervicais",
    "Luxações cervicais",
    "Espondilolistese cervical",
  ],
  coluna_toracica: [
    "Dorsalgia",
    "Hérnia torácica",
    "Escoliose",
    "Hipercifose",
    "Fraturas",
    "Espondilose",
    "Síndrome facetária",
  ],
  coluna_lombar: [
    "Lombalgia",
    "Hérnia lombar",
    "Protusão discal",
    "Abaulamento discal",
    "Estenose lombar",
    "Espondilolistese",
    "Espondilólise",
    "Síndrome facetária",
    "Lombociatalgia",
    "Radiculopatia",
    "Artrose",
    "Fraturas",
    "Instabilidade lombar",
  ],
  ombro: [
    "Fratura da clavícula",
    "Fratura da escápula",
    "Fratura do úmero proximal",
    "Luxação glenoumeral",
    "Luxação AC",
    "Instabilidade anterior",
    "Instabilidade posterior",
    "Instabilidade multidirecional",
    "Tendinite do manguito",
    "Tendinopatia do manguito",
    "Calcificação do manguito",
    "Ruptura parcial do manguito",
    "Ruptura completa do manguito",
    "Bursite subacromial",
    "Síndrome do impacto",
    "Capsulite adesiva",
    "Lesão SLAP",
    "Lesão de Bankart",
    "Lesão de Hill Sachs",
    "Artrose",
    "Osteonecrose",
    "Trauma",
  ],
  braco: [
    "Fratura do úmero",
    "Contusão muscular",
    "Ruptura do bíceps",
    "Ruptura do tríceps",
    "Miosite ossificante",
    "Síndrome compartimental",
    "Trauma",
  ],
  cotovelo: [
    "Epicondilite lateral",
    "Epicondilite medial",
    "Bursite olecraniana",
    "Luxação",
    "Subluxação",
    "Fratura da cabeça do rádio",
    "Fratura do olécrano",
    "Fratura distal do úmero",
    "Osteocondrite dissecante",
    "Instabilidade ligamentar",
  ],
  antebraco: [
    "Fratura do rádio",
    "Fratura da ulna",
    "Fratura de Monteggia",
    "Fratura de Galeazzi",
    "Síndrome compartimental",
    "Lesões musculares",
  ],
  punho: [
    "Fratura de Colles",
    "Fratura de Smith",
    "Fratura de Barton",
    "Fratura do escafoide",
    "Fratura do semilunar",
    "Luxações carpais",
    "Instabilidade escafolunar",
    "Tendinite",
    "Tenossinovite",
    "Cisto sinovial",
  ],
  mao: [
    "Síndrome do túnel do carpo",
    "Dedo em gatilho",
    "Doença de Dupuytren",
    "Tenossinovite de De Quervain",
    "Rizartrose",
    "Artrose",
    "Artrite",
    "Luxações",
    "Fraturas dos metacarpos",
    "Fraturas das falanges",
    "Lesão dos tendões flexores",
    "Lesão dos tendões extensores",
    "Lesões ligamentares",
  ],
  pelve: [
    "Fraturas pélvicas",
    "Disfunção sacroilíaca",
    "Osteíte púbica",
    "Pubalgia",
    "Osteonecrose",
  ],
  quadril: [
    "Coxartrose",
    "Impacto femoroacetabular",
    "Displasia",
    "Bursite trocantérica",
    "Tendinopatia glútea",
    "Lesão do labrum",
    "Luxação",
    "Fratura do colo do fêmur",
    "Fratura transtrocantérica",
    "Necrose avascular",
  ],
  coxa: [
    "Estiramento do quadríceps",
    "Estiramento dos isquiotibiais",
    "Contratura",
    "Ruptura muscular",
    "Contusão",
    "Síndrome compartimental",
  ],
  joelho: [
    "Lesão LCA",
    "Lesão LCP",
    "Lesão LCM",
    "Lesão LCL",
    "Complexo posterolateral",
    "Lesão do menisco medial",
    "Lesão do menisco lateral",
    "Lesão em alça de balde",
    "Lesão radial",
    "Lesão horizontal",
    "Lesão complexa",
    "Condromalácia patelar",
    "Osteocondrite",
    "Lesão condral",
    "Tendinite patelar",
    "Tendinite do quadríceps",
    "Tendinopatia poplítea",
    "Tendinite da pata de ganso",
    "Artrose",
    "Luxação patelar",
    "Instabilidade",
    "Síndrome femoropatelar",
    "Cisto de Baker",
    "Bursites",
    "Osgood-Schlatter",
    "Sinding-Larsen-Johansson",
  ],
  perna: [
    "Estiramento da panturrilha",
    "Ruptura do gastrocnêmio",
    "Ruptura do sóleo",
    "Síndrome compartimental",
    "Periostite tibial",
    "Fratura da tíbia",
    "Fratura da fíbula",
    "Contusão",
  ],
  tornozelo: [
    "Entorse lateral",
    "Entorse medial",
    "Entorse sindesmal",
    "Fratura do maléolo lateral",
    "Fratura do maléolo medial",
    "Fratura bimaleolar",
    "Fratura trimaleolar",
    "Lesão do ligamento deltóide",
    "Instabilidade crônica",
    "Impingement anterior",
    "Tendinopatia do tibial posterior",
    "Tendinopatia dos fibulares",
  ],
  pe: [
    "Fascite plantar",
    "Esporão calcâneo",
    "Fratura do 5º metatarso",
    "Fratura por estresse",
    "Lesão de Lisfranc",
    "Entorse do mediopé",
    "Hallux valgus",
    "Sesamoidite",
    "Contusão",
    "Bolha / dermatose por atrito",
  ],
};

export const PHYSIO_DEFAULT_TREATMENTS: Array<{
  name: string;
  equipment?: string;
  regionId?: string;
}> = [
  { name: "Crioterapia" },
  { name: "Termoterapia" },
  { name: "Eletroterapia TENS" },
  { name: "Ultrassom terapêutico", equipment: "Ultrassom" },
  { name: "Laser terapêutico", equipment: "Laser" },
  { name: "Liberação miofascial" },
  { name: "Mobilização articular" },
  { name: "Fortalecimento muscular" },
  { name: "Propriocepção / equilíbrio" },
  { name: "Bandagem funcional / taping" },
  { name: "Alongamento" },
  { name: "Exercícios terapêuticos" },
  { name: "Retorno progressivo ao treino" },
  { name: "Avaliação / reavaliação" },
  { name: "Massoterapia" },
];
