import type { DynamicReportFieldDefinition } from '../dynamic-reports.types';

const PLAYER_POP = [
  'player.current_bid',
  'player.loaned',
  'player.athletes',
  'player.payroll',
  'people.cafeteria',
] as const;

const EMPLOYEE_POP = ['employee.active_staff', 'employee.by_department', 'people.cafeteria'] as const;

const FINANCIAL_POP = [
  'player.payroll',
  'player.current_bid',
  'player.loaned',
  'player.athletes',
  'employee.active_staff',
  'employee.by_department',
] as const;

export const DYNAMIC_REPORT_FIELDS: DynamicReportFieldDefinition[] = [
  {
    key: 'fullName',
    label: 'Nome completo',
    source: 'player',
    group: 'cadastrais',
    dataType: 'string',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'nickname',
    label: 'Apelido / nome esportivo',
    source: 'player',
    group: 'cadastrais',
    dataType: 'string',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'birthDate',
    label: 'Data de nascimento',
    source: 'player',
    group: 'cadastrais',
    dataType: 'date',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'age',
    label: 'Idade',
    source: 'computed',
    group: 'cadastrais',
    dataType: 'number',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: false,
    exportable: true,
    fieldType: 'calculated',
    populations: [...PLAYER_POP],
  },
  {
    key: 'category',
    label: 'Categoria',
    source: 'player',
    group: 'cadastrais',
    dataType: 'string',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: true,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'position',
    label: 'Posição',
    source: 'player',
    group: 'esportivos',
    dataType: 'string',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: true,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'jerseyNumber',
    label: 'Número da camisa',
    source: 'player',
    group: 'esportivos',
    dataType: 'number',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'sportsSituation',
    label: 'Situação esportiva',
    source: 'player',
    group: 'esportivos',
    dataType: 'string',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: true,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'cpf',
    label: 'CPF',
    source: 'player',
    group: 'documentos',
    dataType: 'string',
    sensitivity: 'document',
    requiredModules: ['adm_rh', 'diretoria'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'rg',
    label: 'RG',
    source: 'player',
    group: 'documentos',
    dataType: 'string',
    sensitivity: 'document',
    requiredModules: ['adm_rh', 'diretoria'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'cbfRegistration',
    label: 'Registro CBF/BID',
    source: 'player',
    group: 'documentos',
    dataType: 'string',
    sensitivity: 'public',
    requiredModules: [],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'loanDestinationClub',
    label: 'Clube de empréstimo',
    source: 'player',
    group: 'emprestimo',
    dataType: 'string',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: ['player.loaned', 'player.athletes', 'people.cafeteria'],
  },
  {
    key: 'loanStartDate',
    label: 'Início do empréstimo',
    source: 'player',
    group: 'emprestimo',
    dataType: 'date',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: ['player.loaned', 'player.athletes'],
  },
  {
    key: 'loanEndDate',
    label: 'Fim do empréstimo',
    source: 'player',
    group: 'emprestimo',
    dataType: 'date',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: ['player.loaned', 'player.athletes'],
  },
  {
    key: 'bankName',
    label: 'Banco',
    source: 'player',
    group: 'bancarios',
    dataType: 'string',
    sensitivity: 'bank',
    requiredModules: ['adm_rh', 'adm_financeiro'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'bankAgency',
    label: 'Agência',
    source: 'player',
    group: 'bancarios',
    dataType: 'string',
    sensitivity: 'bank',
    requiredModules: ['adm_rh', 'adm_financeiro'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'bankAccount',
    label: 'Conta',
    source: 'player',
    group: 'bancarios',
    dataType: 'string',
    sensitivity: 'bank',
    requiredModules: ['adm_rh', 'adm_financeiro'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'bankAccountType',
    label: 'Tipo de conta',
    source: 'player',
    group: 'bancarios',
    dataType: 'string',
    sensitivity: 'bank',
    requiredModules: ['adm_rh', 'adm_financeiro'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'pixKey',
    label: 'PIX',
    source: 'player',
    group: 'bancarios',
    dataType: 'string',
    sensitivity: 'bank',
    requiredModules: ['adm_rh', 'adm_financeiro'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'pixKeyType',
    label: 'Tipo PIX',
    source: 'player',
    group: 'bancarios',
    dataType: 'string',
    sensitivity: 'bank',
    requiredModules: ['adm_rh', 'adm_financeiro'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'officialMatchMinutes',
    label: 'Min. de jogo',
    source: 'computed',
    group: 'esportivos',
    dataType: 'number',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: false,
    exportable: true,
    fieldType: 'calculated',
    populations: [...PLAYER_POP],
  },
  {
    key: 'employeeFullName',
    label: 'Nome completo',
    source: 'employee',
    group: 'cadastrais',
    dataType: 'string',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...EMPLOYEE_POP],
  },
  {
    key: 'department',
    label: 'Departamento',
    source: 'employee',
    group: 'rh',
    dataType: 'string',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: true,
    exportable: true,
    fieldType: 'data',
    populations: [...EMPLOYEE_POP],
  },
  {
    key: 'employeeType',
    label: 'Tipo colaborador',
    source: 'employee',
    group: 'rh',
    dataType: 'string',
    sensitivity: 'public',
    requiredModules: [],
    sortable: true,
    filterable: true,
    exportable: true,
    fieldType: 'data',
    populations: [...EMPLOYEE_POP],
  },
  {
    key: 'employmentContractType',
    label: 'Tipo de vínculo',
    source: 'employee',
    group: 'rh',
    dataType: 'string',
    sensitivity: 'rh',
    requiredModules: ['adm_rh'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...EMPLOYEE_POP, 'player.payroll', 'player.athletes', 'player.current_bid', 'player.loaned'],
  },
  {
    key: 'salary',
    label: 'Salário',
    source: 'employee',
    group: 'financeiro',
    dataType: 'number',
    sensitivity: 'rh',
    requiredModules: ['adm_rh', 'adm_financeiro'],
    sortable: true,
    filterable: false,
    exportable: true,
    fieldType: 'calculated',
    populations: [...FINANCIAL_POP],
  },
  {
    key: 'receivesTransport',
    label: 'Recebe Vale Transporte',
    source: 'computed',
    group: 'financeiro',
    dataType: 'boolean',
    sensitivity: 'rh',
    requiredModules: ['adm_rh'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'calculated',
    populations: [...FINANCIAL_POP],
  },
  {
    key: 'transportAmount',
    label: 'Valor Vale Transporte',
    source: 'computed',
    group: 'financeiro',
    dataType: 'number',
    sensitivity: 'rh',
    requiredModules: ['adm_rh', 'adm_financeiro'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'calculated',
    populations: [...FINANCIAL_POP],
  },
  {
    key: 'receivesMeal',
    label: 'Recebe Alimentação',
    source: 'computed',
    group: 'financeiro',
    dataType: 'boolean',
    sensitivity: 'rh',
    requiredModules: ['adm_rh'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'calculated',
    populations: [...FINANCIAL_POP],
  },
  {
    key: 'mealAmount',
    label: 'Valor Alimentação',
    source: 'computed',
    group: 'financeiro',
    dataType: 'number',
    sensitivity: 'rh',
    requiredModules: ['adm_rh', 'adm_financeiro'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'calculated',
    populations: [...FINANCIAL_POP],
  },
  {
    key: 'receivesCostAllowance',
    label: 'Recebe Ajuda de Custo',
    source: 'computed',
    group: 'financeiro',
    dataType: 'boolean',
    sensitivity: 'rh',
    requiredModules: ['adm_rh'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'calculated',
    populations: [...FINANCIAL_POP],
  },
  {
    key: 'costAllowanceAmount',
    label: 'Valor Ajuda de Custo',
    source: 'computed',
    group: 'financeiro',
    dataType: 'number',
    sensitivity: 'rh',
    requiredModules: ['adm_rh', 'adm_financeiro'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'calculated',
    populations: [...FINANCIAL_POP],
  },
  {
    key: 'receivesImageRights',
    label: 'Recebe Direito de Imagem',
    source: 'computed',
    group: 'financeiro',
    dataType: 'boolean',
    sensitivity: 'rh',
    requiredModules: ['adm_rh'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'calculated',
    populations: [...FINANCIAL_POP],
  },
  {
    key: 'imageRightsAmount',
    label: 'Valor Direito de Imagem',
    source: 'computed',
    group: 'financeiro',
    dataType: 'number',
    sensitivity: 'rh',
    requiredModules: ['adm_rh', 'adm_financeiro'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'calculated',
    populations: [...FINANCIAL_POP],
  },
  {
    key: 'bankHolderName',
    label: 'Titular da conta',
    source: 'employee',
    group: 'bancarios',
    dataType: 'string',
    sensitivity: 'bank',
    requiredModules: ['adm_rh', 'adm_financeiro'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...FINANCIAL_POP],
  },
  {
    key: 'bankHolderCpf',
    label: 'CPF do titular',
    source: 'employee',
    group: 'bancarios',
    dataType: 'string',
    sensitivity: 'document',
    requiredModules: ['adm_rh', 'adm_financeiro'],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...FINANCIAL_POP],
  },
  {
    key: 'athletePhoto',
    label: 'Foto',
    source: 'player',
    group: 'cadastrais',
    dataType: 'string',
    sensitivity: 'public',
    requiredModules: [],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'data',
    populations: [...PLAYER_POP],
  },
  {
    key: 'signature',
    label: 'Assinatura',
    source: 'display',
    group: 'display',
    dataType: 'string',
    sensitivity: 'public',
    requiredModules: [],
    sortable: false,
    filterable: false,
    exportable: true,
    fieldType: 'displayOnly',
    populations: [...PLAYER_POP, ...EMPLOYEE_POP],
  },
];

export function getFieldDefinition(key: string): DynamicReportFieldDefinition | undefined {
  return DYNAMIC_REPORT_FIELDS.find((f) => f.key === key);
}

export function fieldAllowedForPopulation(
  field: DynamicReportFieldDefinition,
  population: string,
): boolean {
  if (field.populations.length === 0) return true;
  return field.populations.includes(population);
}

export function filterFieldsForModules(
  fields: DynamicReportFieldDefinition[],
  moduleSlugs: string[],
  isSuperAdmin: boolean,
): DynamicReportFieldDefinition[] {
  if (isSuperAdmin) return fields;
  return fields.filter((field) => {
    if (field.requiredModules.length === 0) return true;
    return field.requiredModules.some((m) => moduleSlugs.includes(m));
  });
}

export function authorizeRequestedFields(
  requested: string[],
  population: string,
  moduleSlugs: string[],
  isSuperAdmin: boolean,
): { allowed: string[]; stripped: string[] } {
  const allowedKeys = new Set(
    filterFieldsForModules(DYNAMIC_REPORT_FIELDS, moduleSlugs, isSuperAdmin)
      .filter((f) => fieldAllowedForPopulation(f, population))
      .map((f) => f.key),
  );
  const allowed: string[] = [];
  const stripped: string[] = [];
  for (const key of requested) {
    if (!getFieldDefinition(key)) {
      stripped.push(key);
      continue;
    }
    if (allowedKeys.has(key)) allowed.push(key);
    else stripped.push(key);
  }
  return { allowed, stripped };
}
